apiVersion: v2
name: aap-gateway
description: Helm chart for deploying Ansible Automation Platform on Red Hat OpenShift
type: application
version: 1.1.1
appVersion: ">=2.5"
kubeVersion: ">=1.25.0-0"  # OpenShift 4.12+ (minimum for AAP 2.5)
keywords:
  - ansible
  - automation
  - aap
  - openshift
  - redhat
home: https://github.com/Chanoian/aap-gateway-helm
sources:
  - https://github.com/Chanoian/aap-gateway-helm
maintainers:
  - name: Ara Chanoian
    email: ara.chanoian@gmail.com
