apiVersion: v2
name: aap-gateway
description: Helm chart for deploying Ansible Automation Platform on Red Hat OpenShift
type: application
version: 0.1.0
appVersion: "2.6.0-0.1774648945"
keywords:
  - ansible
  - automation
  - aap
  - openshift
home: https://github.com/Chanoian/aap-gateway-helm
sources:
  - https://github.com/Chanoian/aap-gateway-helm
maintainers:
  - name: Ara Chanoian
    email: ara.chanoian@gmail.com 
